/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    FileUpload: typeof import('./components/FileUpload.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LivenessSelfie: typeof import('./components/LivenessSelfie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ValidationResult: typeof import('./components/ValidationResult.vue')['default']
  }
}
